config/routes.rb
Rails.application.routes.draw do

  resources :works, except: [:index, :new]

  resources :clients do
    resources :works, only: [:index, :new]
  end

  devise_for :users

  get 'welcome/index'
  root 'clients#index'

  

end

app/models/client.rb
class Client < ActiveRecord::Base

  belongs_to :user
  has_many :works
  validates :user_id, presence: true
  validates :name, presence: true
  default_scope  { order(:created_at => :desc) }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :clients, :dependent => :destroy
  has_many :works, through: :clients, :dependent => :destroy
end

app/models/work.rb
class Work < ActiveRecord::Base

  belongs_to :client
  belongs_to :user
  validates :title, presence: true
  validates_datetime :start_time
  validates_datetime :end_time
  validates_datetime :end_time, after: :start_time
  default_scope -> { order(created_at: :desc) }


  def time_elapsed
    elapsed = (start_time - end_time).to_i.abs
    hours = elapsed / 3600.0
    return hours.round(2)
  end

  def money_dollars
    if billed == true
      return "$$$$$"
    else
      return "nope."
    end
  end

  def faded
    if billed == true
      return "faded"
    end
  end

  def total_billed
    Work.where(billed: true).time_elapsed.sum
  end

  def time_unbilled
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #before_action :authenticate_user!
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]


  #before_action :load_work #, only: [:new, :show, :edit, :create, :update]

  respond_to :html

  before_action :authenticate_user!
  
  before_filter :require_permission, except: [:index, :new, :create]

  def index
    #@clients = Client.all
    @clients = current_user.clients.paginate(:page => params[:page], :per_page => 50)
    respond_with(@clients)
  end

  def show
    @works = current_user.works
    respond_with(@client)
  end

  def new
    @client = Client.new
    respond_with(@client)
  end

  def edit
  end

  def create
    @client = current_user.clients.build(client_params)
    @client.save
    respond_with(@client)
  end

  def update
    @client.update(client_params)
    respond_with(@client)
  end

  def destroy
    @client.destroy
    respond_with(@client)
  end

  private
    def set_client
      @client = Client.find(params[:id])
    end

    def client_params
      params.require(:client).permit(:name, :user_id)
    end

     def load_work
       @works = works.collect {|work| [work.start_time, work.end_time, work.title, work.description, work.billed, work.client_id]}
     end

      def require_permission
        if current_user != Client.find(params[:id]).user
          redirect_to root_path
          #Or do something else here
        end
      end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  #before_action :load_clients, only: [:new, :edit, :create, :update]

  before_action :find_client

  respond_to :html

  before_action :authenticate_user!

  before_filter :require_permission, except: [:index, :new, :create]
  before_filter :index_permission, only: [:index, :new, :create]

  def index
    @works = @client.works.paginate(:page => params[:page], :per_page => 50)
    #@total_billed = Work.where(billed: true).time_elapsed.sum
    respond_with(@works)
  end

  def show
    respond_with(@work)
    # @work = @client.works.find(params[:id])
    # respond_to do |format|
    #   format.html # show.html.erb
    #   format.xml  { render :xml => @work }
    # end
  end

  def new
    @work = @client.works.build
    respond_with(@work)
  end

  def edit
    @work = @client.works.find(params[:id])
  end

  def create
    @work = @client.works.build(work_params)
    @work.save
    respond_with(@work.client, @work)
  end

  def update
    @work = @client.works.find(params[:id])
    @work.update(work_params)
    respond_with(@work.client, @work)
  end

  def destroy
    @work.destroy
    respond_with(@work.client, @work)
  end

  private
    def set_work
      @work = Work.find(params[:id])
    end

    def work_params
      params.require(:work).permit(:start_time, :end_time, :title, :description, :billed, :client_id, :user_id)
    end

    def load_clients
      @clients = current_user.clients.collect {|client| [client.name, client.id]}
    end

    def find_client
      @client = Client.find(params[:client_id])
    end

    def require_permission
      if current_user != Work.find(params[:id]).client.user
        redirect_to root_path
        #Or do something else here
      end
    end

    def index_permission
      if current_user != Client.find(params[:client_id]).user
        redirect_to root_path
        #Or do something else here
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/clients/_form.html.erb
<%= bootstrap_form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-lg btn-primary btn-block" %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<div class="col-sm-6 col-sm-offset-3">

<h1>Edit Client</h1>

<%= render 'form' %>

<div class="link-action">
&#62;<%= link_to 'Cancel', clients_path %>

</div>

app/views/clients/index.html.erb
<div class="col-sm-8 col-sm-offset-2">

<p id="notice"><%= notice %></p>

<h1>Clients <span class="header-link"> &#62; <%= link_to 'Add a client', new_client_path %></span></h1>


<br>
<br>

<div class="table-responsive">
<table class="table table-striped">

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><h2><%= link_to client.name, client_works_path(client) %></td></h2>
        <!--<td><%# link_to 'Show', client %></td>-->
        <td class="actions"> &#62;<%= link_to 'Edit', edit_client_path(client) %> <br>
       &#62;<%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<%= will_paginate (@clients), renderer: BootstrapPagination::Rails %>

</div>

app/views/clients/new.html.erb
<div class="col-sm-6 col-sm-offset-3">

<h1>Add Client</h1>

<%= render 'form' %>

<div class="link-action">
&#62;<%= link_to 'Cancel', clients_path %>
</div>

</div>

app/views/clients/show.html.erb
<div class="col-sm-6 col-sm-offset-3">

<p id="notice"><%= notice %></p>

<h1>

  <%= @client.name %>
</h1>

<div class="link-action">
&#62;<%= link_to 'Edit', edit_client_path(@client) %><br>
&#62;<%= link_to 'Index', clients_path %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TddThree</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="./" class="navbar-brand"><%= link_to "hourly", root_path, id: "logo" %></a>
    </div>
    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Clients", root_path %></li>
            <li><%= link_to 'Edit account', edit_user_registration_path, :class => 'navbar-link' %> </li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
            <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
          <% end %>
      </ul>
    </nav>
  </div>
</header>

<div class="container main-content">
  <%= yield %>
</div>


    <script type="text/javascript">
      $('.datetimepicker1').datetimepicker({
        step:15,
        // formatTime:'g:i a',
        //mask:true,
        // format:'m/d/Y g:i a',
        minDate:0,
        formatTime:'g:i a',
       // theme:'dark',
        mask:true,
        format:'Y/m/d g:i a',
        validateOnBlur:false,
        formatTimeScroller: 'g:i a' /*uppercase AM/PM now*/

        // disabledDates: ['12.02.2014 10:30','12.08.2014 11:00'], 
        // formatDate:'m.d.Y H:i'
      });
    </script>
</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= link_to "Signout", destroy_user_session_path, method: :delete %>

app/views/works/_form.html.erb
<%= bootstrap_form_for([@work.client, @work]) do |f| %>
  <% if @work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% @work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%# f.select :client_id, @clients %>
  </div>

  <div class="field">
    <%= f.text_field :start_time, class: "datetimepicker1" %>
  </div>
  <div class="field">
    <%= f.text_field :end_time, class: "datetimepicker1" %>
  </div>
  <div class="field">
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.check_box :billed %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-lg btn-primary btn-block" %>
  </div>
<% end %>

app/views/works/edit.html.erb
<div class="col-sm-6 col-sm-offset-3">

<h1>Editing Work</h1>

<%= render 'form' %>

<%= link_to 'Cancel', client_works_path(@work.client) %>

</div>

app/views/works/index.html.erb
<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">

<p id="notice"><%= notice %></p>

<h1>Work <span class="header-link"> &#62; <%= link_to 'Add some work',  new_client_work_path %></span></h1>

<br>
<br>
Time unbilled:<br>
Time billed: <%# total_billed %>
<br>
<br>

<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Time</th>
      <th>Title & Description</th>
      <th><span class="billed-yet">Billed?</span></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @works.each do |work| %>
      <tr class="<%= work.faded %>">
        <td class="hours"> <span class="hours-text"><%= work.time_elapsed %></span><br><%= 'hour'.pluralize %> </td>
        <td>
          <h2><%= link_to work.title, [work.client, work] %></h2>
          <%= work.description %>
        </td>
        <td class="dollars"><%= work.money_dollars %></td>
        <!--<td><%# link_to 'Show', [work.client, work] %></td>-->
        <td class="actions"> &#62;<%= link_to 'Edit', edit_client_work_path(work.client, work) %> <br>
       &#62;<%= link_to 'Destroy', [work.client, work], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<%= will_paginate (@works), renderer: BootstrapPagination::Rails %>

</div>

app/views/works/new.html.erb
<div class="col-sm-6 col-sm-offset-3">

<h1>Add Some Work</h1>

<%= render 'form' %>

<div class="link-action">
&#62;<%= link_to 'Cancel', client_works_path(@work.client) %>
</div>
</div>

app/views/works/show.html.erb
<div class="col-sm-6 col-sm-offset-3">

<p id="notice"><%= notice %></p>

<p>
  <span class="startend">Start… </span><br>
  <%= @work.start_time.strftime("%m/%d/%Y _ %I:%M%p") %>
</p>

<p>
  <span class="startend">End… </span><br>
  <%= @work.end_time.strftime("%m/%d/%Y _ %I:%M%p") %>
</p>

 <h1> <%= @work.title %> </h1>

<p>
  <%= @work.description %>
</p>
. . .
<br>
<p>
  <span class="billed-yet">Billed?</span>
  <%= @work.money_dollars %>
</p>

<div class="link-action">
&#62;<%= link_to 'Edit', edit_client_work_path(@work.client, @work) %> <br>
&#62;<%= link_to 'Index', client_works_path(@work.client) %>
</div>

</div>